import type { MailMessage } from "@code-main/api/mail/contracts";
import type { LabelLike } from "@code-main/api/mail/label-presentation";

// The demo persona reuses the fallback account identity in mail-data.tsx so the
// signed-out product tour and the fallback mailbox tell the same story.
export const demoAccountEmail = "alicia@example.com";
export const demoAccountName = "Alicia Koch";

// Mirrors a real Gmail label list: system labels keep their id as the name and
// user labels carry a display name that label-presentation lowercases.
const demoLabels = [
  { id: "INBOX", name: "INBOX", type: "system" },
  { id: "SENT", name: "SENT", type: "system" },
  { id: "DRAFT", name: "DRAFT", type: "system" },
  { id: "SPAM", name: "SPAM", type: "system" },
  { id: "TRASH", name: "TRASH", type: "system" },
  { id: "UNREAD", name: "UNREAD", type: "system" },
  { id: "IMPORTANT", name: "IMPORTANT", type: "system" },
  { id: "STARRED", name: "STARRED", type: "system" },
  { id: "CATEGORY_SOCIAL", name: "CATEGORY_SOCIAL", type: "system" },
  { id: "CATEGORY_UPDATES", name: "CATEGORY_UPDATES", type: "system" },
  { id: "CATEGORY_FORUMS", name: "CATEGORY_FORUMS", type: "system" },
  { id: "CATEGORY_PROMOTIONS", name: "CATEGORY_PROMOTIONS", type: "system" },
  { id: "Label_design", name: "Design", type: "user" },
  { id: "Label_work", name: "Work", type: "user" },
  { id: "Label_personal", name: "Personal", type: "user" },
  { id: "Label_finance", name: "Finance", type: "user" },
  { id: "Label_travel", name: "Travel", type: "user" },
] satisfies readonly LabelLike[];

export type DemoProviderLabelId = (typeof demoLabels)[number]["id"];

export const demoLabelById: ReadonlyMap<string, LabelLike> = new Map(
  demoLabels.map((label) => [label.id, label]),
);

// A demo message is the provider-shaped row: everything a MailMessage carries
// except the two fields the mailbox service derives from provider labels, plus
// the recipient for outgoing mail. `to` is not part of MailMessage — the real
// mailbox service never surfaces it either — so it stays demo-internal state.
export type DemoMessage = Omit<MailMessage, "labels" | "read"> & {
  readonly providerLabels: readonly DemoProviderLabelId[];
  readonly to?: string;
};

export const demoMessages = [
  {
    date: "2026-07-22T08:00:00.000Z",
    email: "reservations@almadalisboa.example",
    id: "demo-msg-001",
    name: "Alma da Lisboa",
    providerLabels: ["Label_travel"],
    snippet: "Your stay is confirmed for 12–16 May, Rua da Boavista 41, check-in from 15:00.",
    subject: "Booking confirmed — Lisbon, 12–16 May",
    text: "Hi Alicia,\n\nYour stay is confirmed.\n\nRua da Boavista 41, Lisbon\nCheck-in: Tuesday 12 May, from 15:00\nCheck-out: Saturday 16 May, before 11:00\nRoom: Studio with terrace, 2 guests\nTotal paid: €612.00\n\nThe front desk is staffed until 22:00. If you arrive later, reply to this email and we'll leave a key code for you.\n\nSee you in May,\nInês\nAlma da Lisboa",
    threadId: "demo-thread-020",
  },
  {
    date: "2026-07-24T14:30:00.000Z",
    email: "hana.suzuki@northwind.design",
    id: "demo-msg-002",
    name: "Hana Suzuki",
    providerLabels: ["Label_design"],
    snippet: "Recap from the May offsite, plus the three bets we agreed to carry into Q3.",
    subject: "Design offsite recap + the three bets we picked",
    text: "Team,\n\nRecap from the offsite, short version.\n\nThe three bets for the next two quarters:\n1. Onboarding — cut time-to-first-project from 11 minutes to under 4.\n2. Notifications — one settings surface instead of the current four.\n3. Design system — ship elevation and motion tokens so we stop hand-rolling shadows.\n\nEverything else we discussed (icon set refresh, marketing site, illustration style) is parked until November.\n\nThe full notes and the photos of the wall are in the shared drive.\n\nHana",
    threadId: "demo-thread-021",
  },
  {
    date: "2026-07-25T09:00:00.000Z",
    email: "notifications@standupbot.example",
    id: "demo-msg-003",
    name: "Standup Bot",
    providerLabels: ["TRASH"],
    snippet: "Standup notes for 6 July: 4 updates, 1 blocker, 0 absences.",
    subject: "Standup notes — 6 July",
    text: "Standup notes for Monday 6 July.\n\nAlicia — finishing the onboarding v2 audit, no blockers.\nMarcus — pairing on the empty states.\nPriya — roadmap draft out Thursday.\nDevon — blocked on the analytics export, chasing data eng.\n\nUnsubscribe from daily notes in your workspace settings.",
    threadId: "demo-thread-019",
  },
  {
    date: "2026-07-27T10:05:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-004",
    name: demoAccountName,
    providerLabels: ["SENT", "Label_finance"],
    snippet: "July retainer invoice attached — 42 hours at the agreed rate, due 15 August.",
    subject: "Invoice — July retainer (INV-2026-07-A)",
    text: "Hi Rachel,\n\nJuly invoice below.\n\nInvoice: INV-2026-07-A\nPeriod: 1–31 July 2026\nHours: 42 (onboarding audit 18, notifications specs 16, design system 8)\nAmount: $6,300.00\nDue: 15 August 2026\n\nSame bank details as last month. Shout if you need it split across two cost centres again.\n\nThanks,\nAlicia",
    threadId: "demo-thread-023",
  },
  {
    date: "2026-07-28T03:12:00.000Z",
    email: "claims@rewards-center-intl.example",
    id: "demo-msg-005",
    name: "Rewards Center",
    providerLabels: ["SPAM", "UNREAD"],
    snippet: "CONGRATULATIONS!!! You have been selected for a $1,000 gift card. Claim in 24 hours.",
    subject: "CONGRATULATIONS!!! Your $1,000 gift card is waiting",
    text: "CONGRATULATIONS!!!\n\nYour email address has been SELECTED in our monthly customer appreciation draw. A $1,000 gift card is reserved in your name.\n\nTo claim, confirm your details within 24 HOURS. Unclaimed prizes are released to the next winner.\n\nCLAIM NOW >>\n\nThis is not a subscription. Reply STOP to stop.",
    threadId: "demo-thread-018",
  },
  {
    date: "2026-07-29T16:10:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-006",
    name: demoAccountName,
    providerLabels: ["SENT", "Label_design"],
    snippet:
      "Rewrote the three onboarding screens against the new copy rules — take a look before Monday.",
    subject: "Updated onboarding copy for review",
    text: "Marcus,\n\nI rewrote the three onboarding screens against the copy rules we agreed on: verbs first, no more than twelve words a line, no product nouns the user hasn't met yet.\n\nBiggest change is the second screen. The old version explained workspaces before anyone had one, so I moved that explanation into the empty state where it actually lands.\n\nFigma page is \"Onboarding v3 / copy pass\". Comments are open until Monday, then I'll lock it and hand off.\n\nAlicia",
    threadId: "demo-thread-022",
  },
  {
    date: "2026-07-30T07:45:00.000Z",
    email: "ben.okafor@brightpathstudio.com",
    id: "demo-msg-007",
    name: "Ben Okafor",
    providerLabels: ["INBOX", "Label_personal"],
    snippet: "Coffee Thursday before standup? The place on Willow opens at seven now.",
    subject: "Coffee Thursday before standup?",
    text: "Hey,\n\nCoffee Thursday before standup? The place on Willow opens at seven now, so we'd have a proper hour instead of the usual fifteen rushed minutes.\n\nI want to hear how the retainer thing went.\n\nBen",
    threadId: "demo-thread-008",
  },
  {
    date: "2026-07-31T08:00:00.000Z",
    email: "team@framewise.example",
    html: '<div><h1>Two days only</h1><p>30% off Framewise Pro annual. Use code <b>SUMMER30</b> at checkout.</p><a href="https://framewise.example/pro">Upgrade</a></div>',
    id: "demo-msg-008",
    name: "Framewise",
    providerLabels: ["INBOX", "CATEGORY_PROMOTIONS"],
    snippet: "30% off Framewise Pro annual — two days only, code SUMMER30.",
    subject: "Two days only: 30% off Framewise Pro",
    text: "Two days only.\n\n30% off Framewise Pro annual with code SUMMER30. That's unlimited prototypes, shared component libraries, and version history that goes back further than three weeks.\n\nOffer ends Sunday at midnight.\n\nUpgrade: https://framewise.example/pro\nUnsubscribe: https://framewise.example/unsubscribe",
    threadId: "demo-thread-013",
  },
  {
    date: "2026-08-01T19:30:00.000Z",
    email: "notify@linkfolio.example",
    id: "demo-msg-009",
    name: "Linkfolio",
    providerLabels: ["INBOX", "CATEGORY_SOCIAL"],
    snippet: "Ben Okafor wants to connect with you on Linkfolio.",
    subject: "Ben Okafor wants to connect",
    text: "Ben Okafor (Product Designer, Brightpath Studio) wants to connect with you on Linkfolio.\n\nYou have 3 other pending invitations.\n\nView invitation: https://linkfolio.example/invitations",
    threadId: "demo-thread-016",
  },
  {
    date: "2026-08-02T11:05:00.000Z",
    email: "rachel.moreau@kestrelworks.com",
    id: "demo-msg-010",
    name: "Rachel Moreau",
    providerLabels: ["INBOX", "STARRED", "Label_work", "Label_finance"],
    snippet:
      "Legal cleared the renewal. Twelve months, same scope, 6% uplift — need your sign-off by the 14th.",
    subject: "Re: Contract renewal — Kestrel Design Partners",
    text: "Alicia,\n\nLegal cleared the renewal this morning. Terms as discussed: twelve months from 1 September, same scope, 6% rate uplift, thirty-day termination either side.\n\nThe only change from the draft you saw is clause 9 — they wanted the IP assignment to trigger on payment rather than on delivery. I pushed back and they accepted payment or 30 days, whichever comes first.\n\nI need your signature by the 14th so procurement can raise the PO before the quarter closes.\n\nRachel",
    threadId: "demo-thread-007",
  },
  {
    date: "2026-08-03T12:40:00.000Z",
    email: "guild@designsystems-guild.example",
    id: "demo-msg-011",
    name: "Design Systems Guild",
    providerLabels: ["INBOX", "CATEGORY_FORUMS"],
    snippet: 'New replies in "Naming tokens for elevation" — 14 messages since you last read.',
    subject: "[Design Systems Guild] Re: naming tokens for elevation",
    text: '14 new replies in "Naming tokens for elevation".\n\nThe thread has settled into two camps. One wants semantic names (surface, raised, overlay, popover) so tokens survive a redesign. The other wants numeric steps (elevation-0 through elevation-5) because designers reach for them faster and the mapping is obvious.\n\nThe compromise most people seem happy with: numeric primitives, semantic aliases on top.\n\nRead the thread: https://designsystems-guild.example/t/elevation-naming',
    threadId: "demo-thread-017",
  },
  {
    date: "2026-08-03T14:08:00.000Z",
    email: "ben.okafor@brightpathstudio.com",
    id: "demo-msg-012",
    name: "Ben Okafor",
    providerLabels: ["INBOX"],
    snippet:
      "Went through the portfolio refresh — the work is strong, the ordering is fighting you.",
    subject: "Quick feedback on your portfolio refresh",
    text: "Alicia,\n\nWent through the refresh twice. The work is strong; the ordering is fighting you.\n\nThe onboarding case study is your best piece and it's fourth. Anyone skimming leaves before they reach it. Move it first.\n\nSecond thing: three of the five case studies open with process. Nobody outside our industry cares about your process until they care about your outcome. Lead with the number, then earn the process.\n\nSmall stuff — the contact link is a mailto that dies on mobile Safari, and the case study images are 4MB each.\n\nBen",
    threadId: "demo-thread-009",
  },
  {
    date: "2026-08-03T18:22:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-013",
    name: demoAccountName,
    providerLabels: ["SENT"],
    snippet: "Reordering now — you're right that process-first reads as insecure.",
    subject: "Re: Quick feedback on your portfolio refresh",
    text: "Ben,\n\nReordering now. You're right that process-first reads as insecure, and I hadn't noticed I'd done it three times.\n\nFixed the mailto and ran the images through a compressor — they're 180KB each now and I honestly can't tell the difference.\n\nI'll ping you when it's live.\n\nAlicia",
    threadId: "demo-thread-009",
  },
  {
    date: "2026-08-03T19:05:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-014",
    name: demoAccountName,
    providerLabels: ["DRAFT"],
    snippet: "One more thing — would you be up for a second pass once the reorder is live?",
    subject: "Re: Quick feedback on your portfolio refresh",
    text: "One more thing — would you be up for a second pass once the reorder is live? Fresh eyes on the",
    threadId: "demo-thread-009",
  },
  {
    date: "2026-08-04T07:30:00.000Z",
    email: "marcus.chen@northwind.design",
    id: "demo-msg-015",
    name: "Marcus Chen",
    providerLabels: ["INBOX", "IMPORTANT", "Label_design"],
    snippet: "Ready for review whenever you are — v3 cuts the flow from seven screens to four.",
    subject: "Design review: onboarding flow v3",
    text: "Alicia,\n\nv3 is ready for review. Headline: seven screens down to four.\n\nWhat changed:\n- Merged the workspace and team steps. Nobody was creating a team at signup anyway; 4% of accounts did it in the last 90 days.\n- Killed the tour. Completion was 61% and the people who finished it were no more activated than the people who skipped it.\n- Moved the integrations picker into the empty state, so it appears when there's something to integrate with.\n\nOpen question I couldn't resolve: do we still need the \"invite your team\" step if the team step is gone? It tests well but it's the biggest single drop-off in the flow.\n\nFigma: Onboarding v3 / review\n\nMarcus",
    threadId: "demo-thread-001",
  },
  {
    date: "2026-08-04T09:15:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-016",
    name: demoAccountName,
    providerLabels: ["SENT", "Label_design"],
    snippet:
      "Four screens is the right call. Keep the invite step but make it skippable in one tap.",
    subject: "Re: Design review: onboarding flow v3",
    text: "Marcus,\n\nFour screens is the right call, and killing the tour is overdue.\n\nOn the invite step: keep it, but make skipping it one tap instead of a link in the corner. The drop-off is real, but the accounts that invite someone in week one retain roughly twice as well, so it's worth paying for — we just shouldn't trap people.\n\nOne thing I'd push on: the merged workspace step now has three inputs and a file picker above the fold. That's a lot for screen two. Can the avatar move to a later moment?\n\nAlicia",
    threadId: "demo-thread-001",
  },
  {
    date: "2026-08-04T16:44:00.000Z",
    email: "marcus.chen@northwind.design",
    id: "demo-msg-017",
    name: "Marcus Chen",
    providerLabels: ["INBOX", "UNREAD", "IMPORTANT", "Label_design"],
    snippet:
      "Avatar moved to the profile nudge on day three. One tap skip is in. Handing off Friday.",
    subject: "Re: Design review: onboarding flow v3",
    text: "Both done.\n\nAvatar moved out of onboarding entirely — it's now a profile nudge on day three, which is where people actually want to look like themselves.\n\nSkip is a real button, same weight as continue.\n\nI'll hand off to engineering Friday unless you want another pass. Specs are written; I just need your yes.\n\nMarcus",
    threadId: "demo-thread-001",
  },
  {
    date: "2026-08-05T09:12:00.000Z",
    email: "dana.whitfield@brightpathstudio.com",
    id: "demo-msg-018",
    name: "Dana Whitfield",
    providerLabels: ["INBOX", "Label_work"],
    snippet:
      "Can we move Thursday's sync to 2:00pm? The client review ran long and I'd rather not rush ours.",
    subject: "Can we move Thursday's sync to 2:00pm?",
    text: "Hi Alicia,\n\nCan we move Thursday's sync from 11:00 to 2:00pm? The client review before it ran forty minutes long last week and I'd rather not walk into ours already behind.\n\n2:00–2:45 works on my side, and Priya said any afternoon slot is fine for her.\n\nIf Thursday afternoon is bad for you, Friday 10:00 is my other option.\n\nDana",
    threadId: "demo-thread-003",
  },
  {
    date: "2026-08-05T10:31:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-019",
    name: demoAccountName,
    providerLabels: ["SENT", "Label_work"],
    snippet: "2:00pm Thursday works. I'll move the invite and add the roadmap doc to the agenda.",
    subject: "Re: Can we move Thursday's sync to 2:00pm?",
    text: "Dana,\n\n2:00pm Thursday works. I'll move the invite.\n\nCan we add fifteen minutes at the end for the Q3 roadmap doc? Priya's version has three open questions and I'd rather close them live than trade comments for another week.\n\nAlicia",
    threadId: "demo-thread-003",
  },
  {
    date: "2026-08-05T10:00:00.000Z",
    email: "billing@aperturetools.example",
    id: "demo-msg-020",
    name: "Aperture Tools",
    providerLabels: ["INBOX", "CATEGORY_UPDATES", "Label_finance"],
    snippet: "Receipt for INV-20418 — Aperture Tools Team, $144.00 charged to Visa ending 4417.",
    subject: "Receipt for your Aperture Tools subscription (INV-20418)",
    text: "Thanks for your payment.\n\nInvoice: INV-20418\nPlan: Aperture Tools Team (4 seats)\nPeriod: 5 August 2026 – 4 September 2026\nSubtotal: $120.00\nTax: $24.00\nTotal charged: $144.00\nCard: Visa ending 4417\n\nYour next renewal is 4 September 2026. Manage seats or cancel any time from billing settings.\n\nDownload PDF: https://aperturetools.example/receipts/INV-20418",
    threadId: "demo-thread-005",
  },
  {
    date: "2026-08-05T16:20:00.000Z",
    email: "shipping@caldera-supply.example",
    id: "demo-msg-021",
    name: "Caldera Supply",
    providerLabels: ["INBOX", "CATEGORY_UPDATES"],
    snippet: "Order #A-88213 shipped — arriving Friday 8 August, tracking CS449120387.",
    subject: "Your order #A-88213 has shipped",
    text: "Good news — order #A-88213 is on its way.\n\nItems:\n1 × Walnut monitor riser\n2 × Cable channel, 1m\n\nEstimated delivery: Friday 8 August\nTracking: CS449120387\n\nTrack your parcel: https://caldera-supply.example/track/CS449120387",
    threadId: "demo-thread-011",
  },
  {
    date: "2026-08-06T09:15:00.000Z",
    email: "people@northwind.design",
    id: "demo-msg-022",
    name: "Northwind People Ops",
    providerLabels: ["INBOX", "UNREAD"],
    snippet:
      "Your self-review is due Friday 14 August. It's four questions and takes about fifteen minutes.",
    subject: "Self-review due Friday — about fifteen minutes",
    text: "Hi Alicia,\n\nYour self-review is due Friday 14 August.\n\nFour questions:\n1. What did you ship this half that you're proud of?\n2. Where did you get stuck, and what would unstick it next time?\n3. What do you want to be doing more of in the next six months?\n4. Anything your manager should know that they don't?\n\nIt takes most people fifteen minutes. Your manager's review opens once yours is submitted, so please don't leave it to Friday afternoon.\n\nNorthwind People Ops",
    threadId: "demo-thread-010",
  },
  {
    date: "2026-08-06T13:00:00.000Z",
    email: "hello@interfaceweekly.example",
    html: "<div><h2>The Interface Weekly #148</h2><p>Density, and when to break it.</p></div>",
    id: "demo-msg-023",
    name: "The Interface Weekly",
    providerLabels: ["INBOX", "CATEGORY_UPDATES", "UNREAD"],
    snippet:
      "Issue #148: density, and when to break it — plus three teardowns and a font worth stealing.",
    subject: "The Interface Weekly #148 — density, and when to break it",
    text: "Issue #148\n\nDensity, and when to break it\nThe default advice is \"add whitespace\". That advice is written for marketing pages and quietly ruins tools. If your user looks at the same screen for six hours a day, every row of padding is a row of data they now have to scroll for. The question isn't dense or airy — it's whether the eye has a path.\n\nAlso this week:\n- A teardown of Linear's command palette, and why the empty state does most of the work\n- What three years of dark-mode bug reports taught one team about contrast tokens\n- A free grotesk with a proper tabular figure set\n\nRead online: https://interfaceweekly.example/148\nUnsubscribe: https://interfaceweekly.example/unsubscribe",
    threadId: "demo-thread-012",
  },
  {
    date: "2026-08-06T20:15:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-024",
    name: demoAccountName,
    providerLabels: ["DRAFT"],
    snippet:
      "Three open questions for Q3 planning: analytics ownership, the design system budget, and",
    subject: "Notes for Q3 planning",
    text: "Three open questions I want answered before planning:\n\n1. Who owns analytics instrumentation now that Devon has moved teams?\n2. Is the design system budget separate from product design, or are we still borrowing hours?\n3. Do we have a decision on the notifications rewrite, or is it another quarter of patching?\n\n",
    threadId: "demo-thread-025",
  },
  {
    date: "2026-08-07T08:02:00.000Z",
    email: "notify@figmatic.example",
    id: "demo-msg-025",
    name: "Figmatic",
    providerLabels: ["INBOX", "CATEGORY_SOCIAL", "UNREAD"],
    snippet: 'Sofia Alvarez mentioned you in a comment on "Notifications — settings surface".',
    subject: "Sofia Alvarez mentioned you in a comment",
    text: 'Sofia Alvarez mentioned you in a comment on "Notifications — settings surface".\n\n"@alicia this is the pattern I was describing on the call — one list, per-channel toggles, no nested pages. Curious whether your handoff spec matches."\n\nReply in Figmatic: https://figmatic.example/file/notifications-settings',
    threadId: "demo-thread-015",
  },
  {
    date: "2026-08-07T09:30:00.000Z",
    email: "sofia.alvarez@kestrelworks.com",
    id: "demo-msg-026",
    name: "Sofia Alvarez",
    providerLabels: ["INBOX", "UNREAD", "Label_design"],
    snippet:
      "Handoff specs for the notification settings redesign — states, copy, and the migration note.",
    subject: "Handoff: notification settings redesign specs",
    text: "Alicia,\n\nSpecs are ready for the notification settings redesign.\n\nWhat's in there:\n- One settings surface instead of the current four, grouped by what the notification is about rather than which system sends it\n- Per-channel toggles (email, push, in-app) on every row\n- Empty, loading, error, and partial-failure states for the save action\n- Copy for all fourteen notification types, reviewed by content\n\nOne thing I need a decision on: existing users have preferences spread across four screens, and about 9% have contradictory settings (push off globally, push on for mentions). Do we resolve in favour of the specific setting or the global one? I've assumed specific wins, but it's reversible if you disagree.\n\nSofia",
    threadId: "demo-thread-006",
  },
  {
    date: "2026-08-07T17:45:00.000Z",
    email: "tom.bradbury@kestrelworks.com",
    id: "demo-msg-027",
    name: "Tom Bradbury",
    providerLabels: ["INBOX", "UNREAD", "IMPORTANT"],
    snippet: "Intro: Alicia, meet Sofia — she's building the design systems practice at Kestrel.",
    subject: "Intro: Alicia <> Sofia Alvarez (design systems @ Kestrel)",
    text: "Alicia, Sofia — connecting you two, then getting out of the way.\n\nSofia is building the design systems practice at Kestrel. She spent last year untangling a component library that had grown to 340 components, 90 of which nobody could find. She has opinions about tokens that I think you'll enjoy arguing with.\n\nAlicia runs product design at Northwind and has been through the onboarding-and-activation wringer twice. She also writes the clearest handoff specs I've seen, which is why I keep sending people her way.\n\nSofia mentioned she's looking for someone to sanity-check her token naming before it's locked in. Alicia, no obligation, but I suspect it'd be a fun hour for both of you.\n\nOver to you,\nTom",
    threadId: "demo-thread-004",
  },
  {
    date: "2026-08-08T06:20:00.000Z",
    email: "dana.whitfield@brightpathstudio.com",
    id: "demo-msg-028",
    name: "Dana Whitfield",
    providerLabels: ["INBOX", "UNREAD", "Label_work"],
    snippet: "Moved it — Thursday 2:00–3:00pm, and I've added the roadmap doc to the agenda.",
    subject: "Re: Can we move Thursday's sync to 2:00pm?",
    text: "Moved it. Thursday 2:00–3:00pm, invite updated, and I stretched it to a full hour so the roadmap questions get proper airtime rather than the last five minutes.\n\nI've put the doc at the top of the agenda so we hit it while everyone is still awake.\n\nOne ask: could you read Priya's three open questions before Thursday? Two of them are yours to answer.\n\nDana",
    threadId: "demo-thread-003",
  },
  {
    date: "2026-08-08T11:48:00.000Z",
    email: "priya.raman@lumenlabs.io",
    id: "demo-msg-029",
    name: "Priya Raman",
    providerLabels: ["INBOX", "IMPORTANT", "STARRED", "Label_work"],
    snippet:
      "Q3 status, week 32: onboarding on track, notifications slipping a week, analytics blocked.",
    subject: "Q3 roadmap status — week 32",
    text: "Status for week 32.\n\nOnboarding v3 — On track. Four screens, specs handed off Friday, engineering starts Monday. Target ship 28 August. Time-to-first-project is 11m04s today; the goal is under 4 minutes.\n\nNotifications settings — Slipping one week. Specs are done, but the preference migration is bigger than we scoped: 9% of accounts have contradictory settings and we need a documented resolution rule before engineering can start. New target 11 September.\n\nAnalytics instrumentation — Blocked. Devon moved to the platform team on 27 July and nobody has picked up ownership. Three events we need for the onboarding funnel are still not firing, which means we cannot measure the thing we are about to ship. This is the item I most need help with.\n\nDesign system tokens — On track, quietly. Elevation and motion tokens land in the 0.9 release.\n\nOpen questions:\n1. Who owns analytics instrumentation from here?\n2. Specific-setting-wins or global-setting-wins for the notification migration?\n3. Do we hold the onboarding launch if the funnel events are still dark on 28 August?\n\nPriya",
    threadId: "demo-thread-002",
  },
  {
    date: "2026-08-08T15:12:00.000Z",
    email: "devon.park@lumenlabs.io",
    id: "demo-msg-030",
    name: "Devon Park",
    providerLabels: ["INBOX", "UNREAD", "IMPORTANT", "STARRED", "Label_work"],
    snippet:
      "I can keep the analytics events until the end of the month, but someone needs to own them after.",
    subject: "Re: Q3 roadmap status — week 32",
    text: "On the analytics item —\n\nI can keep the three onboarding events alive until 31 August. That covers the launch. After that I genuinely can't; platform on-call starts and I'll be no use to anyone.\n\nThe work to hand over is smaller than it looks: one schema file, one dashboard, and a runbook I've already half-written. Two days of someone's time, not two weeks.\n\nWhat I'd suggest for question 3: don't hold the launch. Ship on 28 August with the events I've kept alive, and treat instrumentation ownership as a separate decision that doesn't get to block a good release.\n\nDevon",
    threadId: "demo-thread-002",
  },
  {
    date: "2026-08-08T18:05:00.000Z",
    email: demoAccountEmail,
    id: "demo-msg-031",
    name: demoAccountName,
    providerLabels: ["DRAFT"],
    snippet:
      "Hi Sofia — Tom introduced us. I'd love the token conversation, and I have a proposal.",
    subject: "Speaking slot at the DesignOps Summit?",
    text: "Hi Sofia,\n\nTom introduced us last week — I'm the one with the onboarding scar tissue.\n\nI'd genuinely enjoy the token naming conversation, and I have a slightly larger proposal: the DesignOps Summit has a joint-talk slot open in October, and \"we untangled 340 components / we cut onboarding from seven screens to four\" is a better talk than either half alone.\n\nNo pressure either way. Happy to start with the hour you were after.\n\n",
    threadId: "demo-thread-024",
  },
  {
    date: "2026-08-09T07:40:00.000Z",
    email: "offers@meridian-print.example",
    html: "<div><h2>Portfolio prints, half price</h2><p>Museum-grade paper. Ends Sunday.</p></div>",
    id: "demo-msg-032",
    name: "Meridian Print",
    providerLabels: ["INBOX", "CATEGORY_PROMOTIONS", "UNREAD"],
    snippet: "Half price on portfolio prints this week — museum-grade paper, ends Sunday.",
    subject: "Half price on portfolio prints — ends Sunday",
    text: "Portfolio prints, half price this week.\n\nMuseum-grade 310gsm cotton rag, pigment inks, no minimum order. A3 from $9, A2 from $16.\n\nOffer ends Sunday at midnight.\n\nShop: https://meridian-print.example/portfolio\nUnsubscribe: https://meridian-print.example/unsubscribe",
    threadId: "demo-thread-014",
  },
] satisfies readonly DemoMessage[];
